### ISSUE TITLE
Stealthy require and tough-cookie?

### ISSUE THREAD

**Issue by Beanow** [bfncs/request-fluture#3]
I'm not sure what you intended with the stealth require setup, so consider this a discussion issue :smile: 

From what I can tell request has a fairly pure API that doesn't modify the module cache for global settings and the like. Tough cookie possibly being the only exception as a simple `{jar: true}` option enables the default global cookie store.

Is this stealth require intended as a reset of the global cookie store?

If so, wouldn't it be more clean to use requests' own features for this:

```js
// Function that creates a new cookie jar.
const freshJar = request.jar();

// This method returns a wrapper around the normal request API that defaults to whatever options you pass to it.
// Note: request.defaults() does not modify the global request API; instead, it returns a wrapper that has your default settings applied to it.
const freshRequest = request.defaults({jar: freshJar});
```

That said, wouldn't it be fine to share the global cookie jar with direct usage of request?

**Comment by bfncs** [comment]
You are right on this one. Back in the days this has been cargo-culty copied from `request-promise-core` because I thought they used it to work around some global state in `request`. After reading your issue I tried to get my head around why they are using it exactly and it [turned out](https://github.com/request/promise-core/blob/cb9d3bc51005d280bd3b1051baba0700ab3d9c4d/README.md#usage-for-request234) to be obviously because they are patching the actual instance of `request` but still want to allow using the vanilla request in the same project. I always thought request-promise-core would wrap request itself much like this module…

However, thanks for getting me looking it up, I'm going to remove the useless stealthy require.
